name = "model_agency"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "i8wj6oqrjj1zr04rcaw06uwr"
name = "Backlog"
tasks = [ ]

[[processes]]
id = "process1"
name = "To Do"
tasks = [ ]

[[processes]]
id = "process2"
name = "In Progress"
tasks = [ ]

[[processes]]
id = "process3"
name = "Done"
tasks = [ ]
